server:
    port: 8081
spring:
  application:
    name: ekafka

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ekafka-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        max.poll.records: 10
        isolation.level: read_committed


kafka-topic:
  name: str-topic
  partitions: 2
  replication-factor: 1