server:
  port: 8091
spring:
  application:
    name: ekafka-consumer
  kafka:
    consumer:
      bootstrap-servers: localhost:9092


kafka-topic:
  name: payment-topic
  partitions: 2
  replication-factor: 1